"""make person_name nullable

Revision ID: e672ee6aecdf
Revises: e721267c7df4
Create Date: 2026-06-04 10:31:32.378142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e672ee6aecdf'
down_revision = 'e721267c7df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.alter_column('person_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.alter_column('person_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
