"""Initial migration

Revision ID: e721267c7df4
Revises: 
Create Date: 2026-06-02 19:36:48.219152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e721267c7df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE VIEW v_default_rate_by_intent AS
        SELECT
            loan_intent,
            COUNT(*) AS total_applications,
            ROUND(CAST(AVG(loan_amnt)AS NUMERIC), 2) AS average_loan_amount,
            ROUND(CAST(AVG(pred_probability) AS NUMERIC), 2) AS average_predicted_probability
        FROM loan_applications
        GROUP BY loan_intent;
    """)
    op.execute("""
        CREATE VIEW v_loss_by_grade AS
        SELECT 
            loan_grade,
            COUNT(*) AS total_applications,
            ROUND(CAST(AVG(expected_loss) AS NUMERIC), 2) AS average_loss_per_grade
        FROM loan_applications
        GROUP BY loan_grade;
    """)
    op.execute("""
        CREATE VIEW v_loan_amount_by_grade AS 
        SELECT 
            loan_grade,
            COUNT(*) AS total_applications,
            ROUND(CAST(AVG(loan_amnt)AS NUMERIC), 2) AS average_loan_amount
        FROM loan_applications
        GROUP BY loan_grade;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_default_rate_by_intent;")
    op.execute("DROP VIEW IF EXISTS v_loss_by_grade;")
    op.execute("DROP VIEW IF EXISTS v_loan_amount_by_grade;")
    # ### end Alembic commands ###
