"""Initial migration

Revision ID: e721267c7df4
Revises: 
Create Date: 2026-06-02 19:36:48.219152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e721267c7df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riskdim')
    op.drop_table('applicantdim')
    op.drop_table('loanfact')
    op.drop_table('financials')
    op.drop_table('loandim')
    op.drop_table('metricsdim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricsdim',
    sa.Column('metrics_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('predicted_default_probability', sa.NUMERIC(precision=2, scale=2), autoincrement=False, nullable=True),
    sa.Column('predicted_loan_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('expected_loss', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('risk', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('metrics_id', name=op.f('metricsdim_pkey'))
    )
    op.create_table('loandim',
    sa.Column('loan_dim_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('loan_intent', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('loan_dim_id', name=op.f('loandim_pkey'))
    )
    op.create_table('financials',
    sa.Column('person_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('person_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('person_home_ownership', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('person_emp_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_intent', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('loan_grade', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('loan_amnt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('loan_int_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('loan_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_percent_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cb_person_default_on_file', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('cb_person_cred_hist_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pred_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pred_status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('expected_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('risk', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('person_id', name=op.f('financials_pkey'))
    )
    op.create_table('loanfact',
    sa.Column('metrics_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_dim_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_dim_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('loan_amnt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('loan_int_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('loan_percent_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('applicantdim',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_home_ownership', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('person_emp_length', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('riskdim',
    sa.Column('default_dim_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('current_loan_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_ever_defaulted', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('credit_history', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('default_dim_id', name=op.f('riskdim_pkey'))
    )
    # ### end Alembic commands ###
