-- DROP TABLE financials;

-- CREATE TABLE financials (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     person_name VARCHAR2(100) NOT NULL,
--     person_age NUMBER NOT NULL,
--     person_income NUMBER NOT NULL,
--     person_home_ownership VARCHAR2(100) NOT NULL,
--     person_emp_length NUMBER NOT NULL,

--     loan_intent VARCHAR2(100) NOT NULL,
--     loan_grade VARCHAR2(5) NOT NULL,
--     loan_amnt NUMBER NOT NULL,
--     loan_int_rate NUMBER NOT NULL,
--     loan_status NUMBER,
--     loan_percent_income NUMBER NOT NULL,

--     cb_person_default_on_file VARCHAR2(5) NOT NULL,
--     cb_person_cred_hist_length NUMBER NOT NULL
-- ); 

SELECT * FROM financials;


-- ALTER TABLE financials MODIFY id GENERATED BY DEFAULT AS IDENTITY;

-- ALTER TABLE financials ADD (
--     pred_probability NUMBER,
--     pred_status VARCHAR2(10)
-- );

-- ALTER TABLE financials ADD (
--     threshold NUMBER,
--     risk VARCHAR2(50)
-- );

-- ALTER TABLE financials ADD (
--     expected_loss NUMBER,
--     decision VARCHAR2(10)
-- );


-- DELETE FROM financials;
-- COMMIT;